"""Produce real, tool-native graph PNGs for the demo (outside the dashboard).

Outputs into this directory:
  cavity_vs_siwave.png   |Z22| overlay: analytic cavity curve vs 601-pt siwave_ng
                         solve, peak deltas annotated  (the physics money shot)
  ballmap_photonx1.png   the actual 45x45 PHOTON-X1 ball map from the graph JSON,
                         colored by role, seeded-defect ball A11 highlighted
  pdn_z.png              is produced separately by pkgtk's own CLI: pkgtk pdn --png

Deterministic; reads only staged open-source-safe files.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).parent
PHYS = HERE.parent / "phys"
PKG = HERE.parent / "pkg"
sys.path.insert(0, str(PHYS))

import cavity_vs_solver as cvs  # noqa: E402  (verified math, reused as-is)

from pkgtk.models.ts_gate import parse_touchstone  # noqa: E402
from pkgtk.oracles.pdn_cavity import (  # noqa: E402
    Cavity,
    find_resonance_peaks,
    z_matrix,
)

DARK = "#0b0e14"
CYAN = "#39c5cf"
AMBER = "#e3b341"


def physics_overlay() -> None:
    s2p = PHYS / "ext12g" / "plane_pair_12g_touchstone.s2p"
    cav = Cavity(a=cvs.A, b=cvs.B, d=cvs.D, epsilon_r=cvs.EPS_R, tan_delta=cvs.TAND)

    freqs, s, z0, _ = parse_touchstone(s2p)
    zs = cvs.s_to_z(s, z0)[:, 1, 1]
    dense = np.geomspace(freqs[0], freqs[-1], 3000)
    zc = z_matrix(dense, cav, cvs.PORTS)[:, 1, 1]

    pk_s = find_resonance_peaks(freqs, cvs.s_to_z(s, z0)[:, 1, 1])
    lin = np.linspace(freqs[0], freqs[-1], 4001)
    pk_c = find_resonance_peaks(lin, z_matrix(lin, cav, cvs.PORTS)[:, 1, 1])

    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(11, 6.5), dpi=150)
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)
    ax.loglog(dense / 1e9, np.abs(zc), color=CYAN, lw=2.0,
              label="pkgtk cavity model (analytic, tier-0)")
    ax.loglog(freqs / 1e9, np.abs(zs), ".", color=AMBER, ms=4, alpha=0.85,
              label="Ansys SIwave siwave_ng (601-pt headless solve)")
    for fs_ in pk_s:
        fc_ = pk_c[np.argmin(np.abs(pk_c - fs_))]
        delta = 100.0 * abs(fs_ - fc_) / fc_
        ax.axvline(fs_ / 1e9, color=AMBER, lw=0.6, alpha=0.35)
        ax.annotate(f"Δ {delta:.2f}%", xy=(fs_ / 1e9, np.abs(zs).max() * 0.55),
                    color="#e6edf3", fontsize=11, ha="center",
                    bbox=dict(boxstyle="round,pad=0.3", fc="#161b22", ec=AMBER, lw=0.8))
    ax.set_xlabel("frequency (GHz)")
    ax.set_ylabel("|Z22| (Ω)")
    ax.set_title("Plane-pair PDN impedance — open-source cavity oracle vs "
                 "commercial solver (same structure)", fontsize=12)
    ax.grid(True, which="both", color="#21262d", lw=0.5)
    ax.legend(frameon=False, loc="lower left")
    fig.tight_layout()
    fig.savefig(HERE / "cavity_vs_siwave.png", facecolor=DARK)
    plt.close(fig)
    print(f"wrote cavity_vs_siwave.png  (solver peaks {[f'{f/1e9:.3f}' for f in pk_s]}"
          f" GHz vs cavity {[f'{f/1e9:.3f}' for f in pk_c]} GHz)")


def ballmap() -> None:
    g = json.loads((PKG / "graph_photonx1.json").read_text(encoding="utf-8"))
    balls = [n for n in g["nodes"] if n.get("kind") == "ball"]
    colors = {"signal": CYAN, "gnd": "#2ea043", "pwr": AMBER, "nc": "#484f58"}

    def pos(n: dict) -> tuple[float, float]:
        if n.get("xy"):
            return float(n["xy"][0]), float(n["xy"][1])
        gr = n["grid"]
        return gr["col"] * 0.8, gr["row"] * 0.8

    plt.style.use("dark_background")
    fig, ax = plt.subplots(figsize=(9, 9), dpi=150)
    fig.patch.set_facecolor(DARK)
    ax.set_facecolor(DARK)
    star = None
    for n in balls:
        x, y = pos(n)
        ident = str(n.get("id", ""))
        if ident == "A11" or ident.endswith("_A11") or ident == "ball_A11":
            star = (x, y)
            continue
        ax.plot(x, y, "o", ms=3.4, color=colors.get(n.get("role", "signal"), CYAN),
                mec="none", alpha=0.9)
    if star:
        ax.plot(*star, "o", ms=9, mfc="none", mec="#f85149", mew=2.0)
        ax.annotate("A11 — seeded defect (beat 2)", xy=star,
                    xytext=(star[0] + 4.0, star[1] + 3.0), color="#f85149",
                    fontsize=11, arrowprops=dict(arrowstyle="->", color="#f85149"))
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_title(f"PHOTON-X1 — {len(balls)} balls, 45×45, 0.8 mm pitch "
                 "(generated by pkgtk.synth)", fontsize=12)
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    for role, c in colors.items():
        ax.plot([], [], "o", color=c, label=role)
    ax.legend(frameon=False, loc="upper right", fontsize=9)
    ax.grid(True, color="#161b22", lw=0.4)
    fig.tight_layout()
    fig.savefig(HERE / "ballmap_photonx1.png", facecolor=DARK)
    plt.close(fig)
    print(f"wrote ballmap_photonx1.png  ({len(balls)} balls, A11 "
          f"{'highlighted' if star else 'NOT FOUND - check id scheme'})")


if __name__ == "__main__":
    physics_overlay()
    ballmap()
    print("done")
