#!/usr/bin/env bash
# pkgtk end-to-end demo: run every wedge on bundled fixtures, leave artifacts/ that a
# stranger can browse. Idempotent; each step echoes the exact command. < 5 min.
set -euo pipefail
cd "$(dirname "$0")/.."

ART=artifacts
rm -rf "$ART"
mkdir -p "$ART"
printf '%s\n' '# Demo artifacts are generated by `make demo`; do not commit contents.' '*' '!.gitignore' > "$ART/.gitignore"
MAN="$ART/MANIFEST.md"
echo "# pkgtk demo artifacts" > "$MAN"
echo "" >> "$MAN"
echo "Generated by \`make demo\`. Each artifact lists the command that produced it." >> "$MAN"
echo "" >> "$MAN"

run() {  # run <artifact> <description> <command...>
  local art="$1"; local desc="$2"; shift 2
  echo "+ $*"
  "$@"
  echo "| \`$art\` | $desc | \`$*\` |" >> "$MAN"
}

echo "| Artifact | Description | Command |" >> "$MAN"
echo "|----------|-------------|---------|" >> "$MAN"

# 1. Ball-map verify: clean synthetic design (false-positive gate) + a seeded defect.
pkgtk verify fixtures/golden/graphs/clean/graph.json \
  --config fixtures/golden/graphs/clean/config.json --json > "$ART/verify_clean.json" \
  && echo "| \`verify_clean.json\` | clean design, zero violations | pkgtk verify ... |" >> "$MAN"
pkgtk verify fixtures/golden/graphs/bijection_multi_assignment/graph.json --json \
  > "$ART/verify_defect.json" || true
echo "| \`verify_defect.json\` | one seeded connectivity defect | pkgtk verify ... |" >> "$MAN"

# 2. ECO diff between two revisions.
pkgtk diff fixtures/golden/diff/revA.json fixtures/golden/diff/revB.json \
  > "$ART/eco_diff.md" || true
echo "| \`eco_diff.md\` | semantic ECO diff report | pkgtk diff revA revB |" >> "$MAN"

# 3. PDN cavity curve + PNG.
pkgtk pdn --png "$ART/pdn_curve.png" --json > "$ART/pdn.json"
echo "| \`pdn_curve.png\` / \`pdn.json\` | PDN |Z| vs frequency | pkgtk pdn --png |" >> "$MAN"

# 4. Escape-capacity verdict.
pkgtk escape --deck fixtures/golden/escape/escape_deck.yaml --pitch-um 800 \
  --land-um 450 --channels 10 --layers 2 --demand 200 --json > "$ART/escape.json" || true
echo "| \`escape.json\` | escape-capacity (over-subscribed) | pkgtk escape ... |" >> "$MAN"

# 5. Template compliance (seeded role swap).
pkgtk template fixtures/golden/templates/swapped.json \
  --template fixtures/golden/templates/template.yaml --json > "$ART/template.json" || true
echo "| \`template.json\` | template role-swap caught | pkgtk template ... |" >> "$MAN"

# 6. Touchstone quality gate (non-passive known-bad).
python -c "import json; from pkgtk.models.ts_gate import gate; \
open('$ART/touchstone.json','w').write(json.dumps(gate('fixtures/golden/models/touchstone/nonpassive.s2p'), indent=2))"
echo "| \`touchstone.json\` | Touchstone passivity reject | ts_gate(nonpassive.s2p) |" >> "$MAN"

# 7. Geometry lint + clickable lyrdb (only if klayout is available).
if python -c "import klayout.db" 2>/dev/null; then
  pkgtk check fixtures/golden/lint/width_min/in.gds \
    --deck fixtures/golden/lint/test_deck.yaml \
    --layers fixtures/golden/lint/width_min/layers.yaml \
    --out-json "$ART/lint_violations.json" --out-lyrdb "$ART/out.lyrdb" || true
  echo "| \`lint_violations.json\` / \`out.lyrdb\` | geometry DRC + clickable markers | pkgtk check ... |" >> "$MAN"
else
  echo "| (skipped) | geometry lint - klayout not installed | pkgtk check ... |" >> "$MAN"
fi

echo ""
echo "Demo complete. Artifacts in $ART/ (see MANIFEST.md)."
